CREATE TABLE downstream_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    image_url TEXT NOT NULL,
    info_url TEXT NOT NULL,
    description TEXT NOT NULL,
    start_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    end_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    genre TEXT NOT NULL,
    platform TEXT NOT NULL
);