CREATE TYPE genre_type AS ENUM (
    'dubstep',
    'trap',
    'house',
    'techno',
    'trance',
    'dnb',
    'other'
);

CREATE TABLE downstream_genres (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre genre_type
);