CREATE TABLE downstream_schedule (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INTEGER REFERENCES downstream_events(id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES downstream_users(id) ON DELETE SET NULL
);