CREATE TABLE downstream_events_genres {
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INTEGER REFERENCES downstream_events(id) ON DELETE SET NULL,
    genre_id INTEGER REFERENCES downsteram_genres(id) ON DELETE SET NULL
};