CREATE TABLE downstream_events_users {
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event REFERENCES downstream_events(id) ON DELETE SET NULL,
    user REFERENCES downstream_users(id) ON DELETE SET NULL
};